theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

url: "https://infominer.id/"
repository: "infominer33/infominer33.github.io"

title: "infominer.id — Information Discovery"
description: "Research Based Content - Bitcoin, Blockchain Development, Cryptocurrency, Decentralized-Identity, Data Science, SEO, Tech-Trends and History."
image: "https://infominer.id/images/infominer.png"
twitter:
  card: "summary_large_image"
  title: "infominer.id — Information Discovery"
  description: "Research Based Content - Bitcoin, Blockchain Development, Cryptocurrency, Decentralized-Identity, Data Science, SEO, Tech-Trends and History."
  image: "https://infominer.id/images/infominer.png"

