theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
title: infominer.id
description: Research Consultant and Content Creation
url: infominer.id
logo: /infominer.png
twitter:
  username: cryptinfominer
  card: ⚡Research Consultant and Research Driven Content⚡Crypto Generalist⚡Bitcoin Fundamentalist⚡
