title:       ⧉ Infominer 
description: Research Based Content — Bitcoin, Blockchain-History, Development, Decentralized-Identity, Cryptocurrency and Related Subjects.

theme: jekyll-theme-slate
plugins:
    - jekyll-seo-tag
    - jekyll-paginate

url:         https://infominer.id/
logo:        "https://infominer.id/images/crypt0library.png"
image:       "https://infominer.id/images/infominer.png"

twitter:
  card:        summary
  username:    infominer33
  title:       infominer.id — Information Discovery
  description: Research Based Content - Bitcoin, Crypto-History, Blockchain Development, Decentralized-Identity, Cryptocurrency and related subjects.
  image:       "https://infominer.id/images/infominer.png"


social:
  name: Infominer
  links:
    - https://twitter.com/infominer33
    - https://www.linkedin.com/in/infominer/
    - https://github.com/infominer33
    - https://tippin.me/@infominer33

