plugins:
    - jekyll-seo-tag
    - jekyll-github-metadata
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-mentions

jekyll-mentions: https://twitter.com

theme: jekyll-theme-slate

url           : "https://infominer.id"
title         : "Information Discovery"
description   : Research Driven Content—Bitcoin, Blockchain, Self Sovereign Identity, Web Technologies, Development, and Tech History.
author        : "⧉ Infominer"
logo          : "https://infominer.id/images/crypt0library.png"
repository    : "infominer33/infominer33.github.io"
github        : [metadata]

twitter:
  creator     : infominer33
  title       : "Information Discovery"
  description : Research Driven Content—Bitcoin, Blockchain, Self Sovereign Identity, Web Technologies, Development, and Tech History.
  image       : "https://infominer.id/DIDecentralized/infominer.png"
  card        : "summary"

social:
  name: Infominer
  links:
    - https://twitter.com/infominer33
    - https://www.linkedin.com/in/infominer/
    - https://github.com/infominer33
    - https://tippin.me/@infominer33

google_analytics: UA-132558656-1