theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
title: infominer.id
description: Information Discovery —Portfolio and Contact— Bitcoin, Blockchain, Development, Decentralized-Identity, Cryptography, Data Science, Programming, SEO, Cryptocurrency, Related Tech-Trends and History. Information Dense Content and Research Consultant.
url: infominer.id
logo: /infominer.png
twitter:
  username: cryptinfominer
  card: ⚡Research Consultant and Research Driven Content⚡Crypto Generalist⚡Bitcoin Fundamentalist⚡
