theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

url: infominer.id
header: https://infominer.id/images/infominer.png

title: " | Information Discovery"
description: "Information Dense Content - Bitcoin, Blockchain Development, Cryptocurrency, Decentralized-Identity, Data Science, SEO, Tech-Trends and History."
image: images/infominer.png

twitter:
  image: images/infominer.png
  title: " | Information Discovery"
  description: "Information Dense Content - Bitcoin, Blockchain Development, Cryptocurrency, Decentralized-Identity, Data Science, SEO, Tech-Trends and History."