theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
title: infominer.id
description: Personal Portfolio and Contact Page — Research Consultant and Content Creator — Bitcoin, Blockchain, Development, Cryptography, Data Science, Programming, Cryptocurrency, Decentralized-Identity, Related Tech-Trends and History — Freelance Writer and Research Assistant.
url: infominer.id
logo: /infominer.png
twitter:
  username: cryptinfominer
  card: ⚡Research Consultant and Research Driven Content⚡Crypto Generalist⚡Bitcoin Fundamentalist⚡
