theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

title: "infominer.id — Research Enthusiast" 
description: Research Consultant and Information Dense Content. Bitcoin, Blockchain Development, Cryptocurrency, Decentralized-Identity, Data Science, SEO, Tech-Trends and History.
url: infominer.id
repository: infominer33/infominer33.github.io
header: https://infominer.id/images/infominer.png


twitter_user: infominer33
twitter_card: true
twitter_image: https://infominer.id/images/infominer.png

