theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
title: "infominer.id — Information Disovery" 
description: "Research Consultant and Information Dense Content. Bitcoin, Blockchain Development, Cryptocurrency, Decentralized-Identity, Data Science, SEO, Tech-Trends and History." 
url: "infominer.id"
logo: "https://infominer.id/images/infominer.png"
twitter:
  username: "infominer33"
  card: "📚Perpetual Student 📖 ฿itcoin📈 Blockchain📊Crypto-Ⓐ 📝 Research Driven Content 📡"
repository: "infominer33/infominer33.github.io"
image: "https://infominer.id/images/infominer.png"
