theme: jekyll-theme-slate
plugins:
    - jekyll-seo-tag

url:         https://infominer.id/
logo:        "https://infominer.id/images/crypt0library.png"
repository:  infominer33/infominer33.github.io

twitter:
  card:        summary_large_image
  username:    infominer33

social:
  name: Infominer
  links:
    - https://twitter.com/infominer33
    - https://www.linkedin.com/in/infominer/
    - https://github.com/infominer33
    - https://tippin.me/@infominer33

