theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
title: infominer.id
description: Personal Portfolio and Contact Page — Research Consultant and Content Creator — I ask my clients the right questions, to provide the results they need — Bitcoin, Blockchain, Development, Decentralized-Identity, Cryptography, Data Science, Programming, SEO, Cryptocurrency, Related Tech-Trends and History.
url: infominer.id
logo: /infominer.png
twitter:
  username: cryptinfominer
  card: ⚡Research Consultant and Research Driven Content⚡Crypto Generalist⚡Bitcoin Fundamentalist⚡
