theme: jekyll-theme-time-machine
plugins:
  - jekyll-seo-tag
title: infominer.id
description: Contact Details and Portfolio
url: infominer.id
twitter:
  username: cryptinfominer
  card: ⚡Research Consultant and Research Driven Content⚡Crypto Generalist⚡Bitcoin Fundamentalist⚡
