theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
title: infominer.id
description: Information Dense Content, Research Consulting. Bitcoin, Blockchain, Development, Decentralized-Identity, Cryptography, Data Science, Programming, SEO, Cryptocurrency, Related Tech-Trends and History. 
url: infominer.id
logo: /infominer.png
twitter:
  username: cryptinfominer
  card: ฿itcoin Fundamentalist 📈Blockchain Generalist 📚Organized Link Collector 📖Research Driven Content📡
