plugins:
    - jekyll-seo-tag
    - jekyll-github-metadata
    - jekyll-redirect-from
    - jekyll-sitemap
    - jekyll-mentions

jekyll-mentions: "https://twitter.com"

url           : "https://infominer.id"
title         : "Information Discovery"
description   : "Decentralized Identity, Bitcoin-History, Web-Development, Research-Consulting, Information Dense Content."
tagline       : Research Driven Content        

author: 
  name  : "⧉ Infominer"
  url   : https://twitter.com/@infominer33
  email : "infominer@protonmail.com"

logo          : "https://infominer.id/images/crypt0library.png"
github        : [metadata]

repository    : "infominer33/infominer33.github.io"

twitter:
  creator     : infominer33
  site        : infominer33
  title       : "Information Discovery"
  description : "Decentralized Identity, Bitcoin-History, Web-Development, Research-Consulting, Information Dense Content."
  image       : "https://infominer.id/DIDecentralized/infominer.png"
  card        : "summary"

social:
  name: Infominer
  links:
    - https://twitter.com/infominer33
    - https://www.linkedin.com/in/infominer/
    - https://github.com/infominer33
    - https://tippin.me/@infominer33

google_analytics: UA-132558656-1



sass:
  sass_dir:          _sass
  style:            :compressed
