theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

url: "infominer.id"
logo: "https://infominer.id/images/infominer.png"
repository: "infominer/infominer33.github.io"

twitter:
  username: "infominer33"
  card:  "📚Perpetual Student 📖 ฿itcoin📈 Blockchain📊Crypto-Ⓐ 📝 Research Driven Content 📡"
