theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

url: "https://infominer.id"
repository: "infominer33/infominer33.github.io"
header: "https://infominer.id/images/infominer.png"
