theme: jekyll-theme-slate

title: infominer.id — Information Discovery
description: Research Based Content - Bitcoin, Blockchain Development, Cryptocurrency, Decentralized-Identity, Data Science, SEO, Tech-Trends and History.

plugins:
  - jekyll-seo-tag


url: https://infominer.id/

author: Infominer

twitter:
  card: summary_large_image
  site: @infominer33
  creator: @infominer33
  title: infominer.id — Information Discovery
  description: Research Based Content - Bitcoin, Blockchain Development, Cryptocurrency, Decentralized-Identity, Data Science, SEO, Tech-Trends and History.
  image: /images/infominer.png

logo: /images/crypt0library.png

social:
  name: Infominer
  links:
    - https://twitter.com/infominer33
    - https://www.linkedin.com/in/infominer/
    - https://github.com/infominer33
    - https://tippin.me/@infominer33

