theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag

title: infominer.id — Information Discovery
description: Research Based Content - Bitcoin, Blockchain Development, Cryptocurrency, Decentralized-Identity, Data Science, SEO, Tech-Trends and History.

url: https://infominer.id/

twitter:
  card: summary_large_image
  creator: @infominer33

logo: /images/crypt0library.png

social:
  name: Infominer
  links:
    - https://twitter.com/infominer33
    - https://www.linkedin.com/in/infominer/
    - https://github.com/infominer33
    - https://tippin.me/@infominer33

