title:       ⧉ Infominer 
description: Research Based Content — Bitcoin, Blockchain-History, Development, Decentralized-Identity, Cryptocurrency and Related Subjects.


plugins:
    - jekyll-seo-tag
    - jekyll-github-metadata
    - jekyll-redirect-from
    
theme: jekyll-theme-slate

url           : "https://infominer.id"
logo          : "https://infominer.id/images/crypt0library.png"
image         : "https://infominer.id/images/infominer.png"
repository    : "infominer33/infominer33.github.io"
github        : [metadata]

twitter:
  card        : summary
  title       : infominer.id — Information Discovery
  description : Research Based Content - Bitcoin, Crypto-History, Blockchain Development, Decentralized-Identity, Cryptocurrency and related subjects.
  image       : "https://infominer.id/images/infominer.png"


social:
  name: Infominer
  links:
    - https://twitter.com/infominer33
    - https://www.linkedin.com/in/infominer/
    - https://github.com/infominer33
    - https://tippin.me/@infominer33

og:
  image:
    width  : "225"
    height : "225" 
  title       : "Information Discovery"
  description : "Research Driven Content&mdash;BItcoin, Blockchain, Crypto, Self-Sovereign Identity, Development, History."
  url         : "https://infominer.id"
  image       : "https://infominer.id/images/og-image.jpg"
  type        : "website"