theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
title: infominer.id
description: Contact Details and Portfolio
url: infominer.id
logo: http://i.imgur.com/1po9lPM.png
twitter:
  username: cryptinfominer
  card: ⚡Research Consultant and Research Driven Content⚡Crypto Generalist⚡Bitcoin Fundamentalist⚡
