theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
title: infominer.id
description: Information Dense Content and Research Consultant. Bitcoin, Blockchain Development, Decentralized-Identity, Programming, Data Science, SEO, Tech-Trends and Tech-History. 
url: infominer.id
logo: /infominer.png
twitter:
  username: infominer33
  card: 📚Perpetual Student 📖 ฿itcoin📈 Blockchain📊Crypto-Ⓐ 📝 Research Driven Content 📡
