theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

url: "infominer.id"
repository: "infominer/infominer33.github.io"

title: "infominer.id — Information Discovery"
description: "Research Based Content - Bitcoin, Blockchain Development, Cryptocurrency, Decentralized-Identity, Data Science, SEO, Tech-Trends and History."
image: "images/infominer.png"
twitter:
  card: "summary_large_image"
  username: "infominer33"
  title: "infominer.id — Information Discovery"
  description: "Research Based Content - Bitcoin, Blockchain Development, Cryptocurrency, Decentralized-Identity, Data Science, SEO, Tech-Trends and History."
