locale                   : "en-US"
title                    : "Information Discovery"
title_separator          : "-"
name                     : "⧉ Infominer"
description              : "Decentralized Identity, Bitcoin-History, Web-Development, Research-Consulting, Information Dense Content."
url           : "https://infominer.id"
base_url      : ""
repository    : "infominer33/infominer33.github.io"
teaser                   : "https://infominer.id/android-chrome-256x256.png"
logo                     : "https://infominer.id/images/88.png"
masthead_title           : "Information Discovery - Research Driven Content"

theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"



# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from
  - jekyll-sitemap


# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true

 provider               : google
 google:
    tracking_id          : UA-132558656-1
    anonymize_ip         : true

github        : [metadata]

twitter:
  title       : "Information Discovery"
  description : "Decentralized Identity, Bitcoin-History, Web-Development, Research-Consulting, Information Dense Content."
  image       : "https://infominer.id/DIDecentralized/infominer.png"
  card        : "summary"

social:
  name: Infominer
  links:
    - https://twitter.com/infominer33
    - https://www.linkedin.com/in/infominer/
    - https://github.com/infominer33
    - https://tippin.me/@infominer33

