theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
title: infominer.id
description: Research Consultant and Content Creator — Personal Portfolio and Contact Page — Bitcoin, Blockchain, Cryptography, History, Decentralized-Identity — Freelance Copy-Writer and Research Assistant
url: infominer.id
logo: /infominer.png
twitter:
  username: cryptinfominer
  card: ⚡Research Consultant and Research Driven Content⚡Crypto Generalist⚡Bitcoin Fundamentalist⚡
