title:       ⧉ Infominer 
description: Research Driven Content—Bitcoin, Blockchain, Self Sovereign Identity, Web Technologies, Development, and Tech History.


plugins:
    - jekyll-seo-tag
    - jekyll-github-metadata
    - jekyll-redirect-from
    
theme: jekyll-theme-slate


type          : "website"
url           : "https://infominer.id"
title         : "Information Discovery"
description   : Research Driven Content—Bitcoin, Blockchain, Self Sovereign Identity, Web Technologies, Development, and Tech History.
author        : "⧉ Infominer"
logo          : "https://infominer.id/images/crypt0library.png"
repository    : "infominer33/infominer33.github.io"
github        : [metadata]

twitter:
  card        : summary_large_image
  title       : infominer.id — Information Discovery
  description : Research Driven Content—Bitcoin, Blockchain, Self Sovereign Identity, Web Technologies, Development, and Tech History.
  image       : "https://infominer.id/images/og-image.jpg"


social:
  name: Infominer
  links:
    - https://twitter.com/infominer33
    - https://www.linkedin.com/in/infominer/
    - https://github.com/infominer33
    - https://tippin.me/@infominer33

  
