theme: jekyll-theme-slate
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

url: "infominer.id"
logo: "https://infominer.id/images/infominer.png"
repository: "infominer/infominer33.github.io"

title: "infominer.id — Information Discovery"
description: "Research Based Content - Bitcoin, Blockchain Development, Cryptocurrency, Decentralized-Identity, Data Science, SEO, Tech-Trends and History."
image: "images/infominer.png"

twitter:
  username: "infominer33"
  image: "images/infominer.png"
  title: "infominer.id — Information Discovery"
  description: "Research Based Content - Bitcoin, Blockchain Development, Cryptocurrency, Decentralized-Identity, Data Science, SEO, Tech-Trends and History."
